"""
Shared REST fixtures for KAN-1 automation tests.
Generated by QA Script Generator.
"""
from __future__ import annotations
import os
import pytest
import requests

BASE_URL = os.getenv("API_BASE_URL", 'https://jsonplaceholder.typicode.com')
DEFAULT_TIMEOUT = int(os.getenv("API_TIMEOUT", "30"))


@pytest.fixture(scope="session")
def api_key() -> str:
    return os.getenv("API_KEY", 'reqres_959cf69c96f743028cc85c9a64b685c9').strip()


@pytest.fixture(scope="session")
def api_client(api_key: str) -> requests.Session:
    session = requests.Session()
    session.headers.update({"Content-Type": "application/json", "Accept": "application/json"})
    if api_key:
        # Cover common mock API auth styles (Bearer + x-api-key, e.g. ReqRes)
        session.headers.update({
            "Authorization": f"Bearer {api_key}",
            "x-api-key": api_key,
        })
    return session


@pytest.fixture(scope="session")
def base_url() -> str:
    return BASE_URL.rstrip("/")
