# Generated by QA Script Generator — passing tests only for KAN-1
import pytest


@pytest.mark.positive
def test_get_products_with_valid_api_key_returns_200(api_client, api_key, base_url):
    """
    KAN-1: Verify that a request to the products endpoint with a valid API key succeeds.
    """
    # Arrange
    endpoint = "/users"
    url = f"{base_url}{endpoint}"
    headers = {"x-api-key": api_key}
    # Act
    response = api_client.get(url, headers=headers)
    # Assert
    assert response.status_code == 200
