# Generated by QA Script Generator — single test: test_kan_1::test_get_products_returns_paginated_product_list_with_valid_api_key for KAN-1
import re
import pytest


@pytest.mark.positive
def test_get_products_returns_paginated_product_list_with_valid_api_key(api_client, api_key, base_url):
    """KAN-1: Verify that a GET request to /products with a valid API key returns a 200 response,
    includes required pagination fields, and provides correctly paginated product objects with required attributes and positive integer IDs."""
    # Arrange
    endpoint = "/products"
    url = f"{base_url}{endpoint}"
    headers = {"x-api-key": api_key}
    params = {"page": 1, "per_page": 6}

    # Act
    response = api_client.get(url, headers=headers, params=params)

    # Assert
    assert response.status_code == 200
    json_body = response.json()
    for field in ("page", "per_page", "total", "total_pages", "data"):
        assert field in json_body
    assert json_body["page"] == 1
    assert json_body["per_page"] == 6
    assert isinstance(json_body["data"], list)
    assert len(json_body["data"]) == 6
    for product in json_body["data"]:
        for key in ("id", "name", "year", "color", "pantone_value"):
            assert key in product
        assert isinstance(product["id"], int) and product["id"] > 0
