# Generated by QualityPilot — shared fixtures for QualityPilot-generated UI tests.
#
# These fixtures only apply to tests in this folder. Credentials are NEVER stored
# here; provide them through the environment when running the suite:
#
#   QP_USERNAME / QP_PASSWORD   test account (email + password, or phone + OTP)
#   QP_BASE_URL                 override the app under test   (default below)
#   QP_LOGIN_URL, QP_LOGIN_TYPE, QP_LANDING_PATH   optional overrides
#   QP_HEADED=1                 show the browser
#
# Requires: pytest, pytest-asyncio, playwright  (then: playwright install chromium)
import importlib.util
import os
from pathlib import Path

import pytest
import pytest_asyncio
from playwright.async_api import async_playwright

_spec = importlib.util.spec_from_file_location("qp_login", Path(__file__).with_name("qp_login.py"))
qp_login = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(qp_login)

DEFAULTS = {
    'app_url': 'http://localhost:5173',
    'login_url': 'http://localhost:5173/login',
    'login_type': 'email_password',
    'landing_path': '/',
    'email_selector': 'input[type=email]',
    'password_selector': 'input[type=password]',
    'phone_selector': 'input[type=tel]',
    'agree_terms_selector': '',
    'send_otp_selector': "button:has-text('OTP')",
    'otp_selector': "input[placeholder*='OTP' i]",
    'submit_selector': "button:has-text('Sign in')",
}


def _env(name: str, key: str = "") -> str:
    return os.environ.get(name) or DEFAULTS.get(key, "")


def _credentials(base_url: str) -> dict:
    creds = {k: v for k, v in DEFAULTS.items() if v}
    creds.update({
        "username": os.environ.get("QP_USERNAME", ""),
        "password": os.environ.get("QP_PASSWORD", ""),
        "app_url": base_url,
        "login_url": _env("QP_LOGIN_URL", "login_url") or base_url,
        "login_type": _env("QP_LOGIN_TYPE", "login_type") or "email_password",
        "landing_path": _env("QP_LANDING_PATH", "landing_path") or "/",
    })
    return creds


@pytest.fixture(scope="session")
def base_url() -> str:
    url = _env("QP_BASE_URL", "app_url").rstrip("/")
    if not url:
        pytest.skip("QP_BASE_URL is not set")
    return url


@pytest.fixture
def username() -> str:
    value = os.environ.get("QP_USERNAME", "")
    if not value:
        pytest.skip("QP_USERNAME is not set")
    return value


@pytest.fixture
def password() -> str:
    value = os.environ.get("QP_PASSWORD", "")
    if not value:
        pytest.skip("QP_PASSWORD is not set")
    return value


@pytest_asyncio.fixture
async def page(request, base_url):
    """A fresh browser page; signed in first unless the test is itself a login test."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=os.environ.get("QP_HEADED", "") not in ("1", "true"))
        try:
            context = await browser.new_context(viewport={"width": 1280, "height": 720})
            pg = await context.new_page()
            pg.set_default_timeout(30000)
            creds = _credentials(base_url)
            if "username" not in request.fixturenames and creds["username"] and creds["password"]:
                await qp_login.perform_login(pg, creds)
                landing = creds["landing_path"].strip()
                if landing and landing != "/":
                    await pg.goto(base_url + (landing if landing.startswith("/") else "/" + landing), wait_until="load")
            yield pg
        finally:
            await browser.close()
