# Generated by QualityPilot — login helpers used by conftest.py (copy of login_runtime.py).
"""Standalone Playwright login helpers (copied into runner subprocess tmpdir)."""
from __future__ import annotations

from urllib.parse import urlparse

from playwright.async_api import Locator, Page

PHONE_FIELD_FALLBACKS = (
    '[id="Mobile Number"]',
    "input[type=tel]",
    "input[type=number]",
    "input[placeholder*='mobile' i]",
    "input[placeholder*='phone' i]",
)


async def resolve_locator(page: Page, selector: str, *, timeout_ms: int = 20000) -> Locator | None:
    sel = (selector or "").strip()
    if not sel:
        return None
    candidates = [sel] if sel.startswith("xpath=") else [p.strip() for p in sel.split(",") if p.strip()]
    for candidate in candidates:
        loc = page.locator(candidate).first
        try:
            await loc.wait_for(state="visible", timeout=timeout_ms)
            if await loc.count():
                return loc
        except Exception:
            continue
    return None


async def wait_for_phone_field(page: Page, creds: dict[str, str], *, timeout_ms: int = 30000) -> Locator:
    """Wait for SPA hydration and the phone input to become visible."""
    try:
        await page.wait_for_load_state("load", timeout=min(timeout_ms, 15000))
    except Exception:
        pass
    try:
        await page.wait_for_load_state("networkidle", timeout=min(timeout_ms, 12000))
    except Exception:
        pass

    selectors: list[str] = []
    configured = (creds.get("phone_selector") or "").strip()
    if configured:
        if configured.startswith("xpath="):
            selectors.append(configured)
        else:
            selectors.extend(p.strip() for p in configured.split(",") if p.strip())
    for fallback in PHONE_FIELD_FALLBACKS:
        if fallback not in selectors:
            selectors.append(fallback)

    per_selector = max(timeout_ms // max(len(selectors), 1), 5000)
    for selector in selectors:
        field = await resolve_locator(page, selector, timeout_ms=per_selector)
        if field is not None:
            return field
    raise RuntimeError("Phone input not found")


async def fill_otp(page: Page, otp_value: str, otp_selector: str) -> None:
    sel = (otp_selector or "").strip()
    if sel:
        multi = page.locator(sel if sel.startswith("xpath=") else sel)
        count = await multi.count()
        if count >= len(otp_value):
            for i, digit in enumerate(otp_value):
                await multi.nth(i).fill(digit)
            return

    split_inputs = page.locator("input[maxlength='1']")
    if await split_inputs.count() >= len(otp_value):
        for i, digit in enumerate(otp_value):
            await split_inputs.nth(i).fill(digit)
        return

    otp_field = await resolve_locator(page, otp_selector)
    if otp_field is None:
        raise RuntimeError("OTP input not found")
    await otp_field.fill(otp_value)


async def perform_phone_otp_login(page: Page, creds: dict[str, str]) -> None:
    username = creds.get("username", "")
    password = creds.get("password", "")

    phone_field = await wait_for_phone_field(page, creds)
    await phone_field.fill(username)

    agree_sel = creds.get("agree_terms_selector", "")
    if agree_sel:
        terms = await resolve_locator(page, agree_sel)
        if terms is not None:
            try:
                if not await terms.is_checked():
                    try:
                        await terms.check(force=True)
                    except Exception:
                        await terms.evaluate(
                            """el => {
                                el.checked = true;
                                el.dispatchEvent(new Event('input', { bubbles: true }));
                                el.dispatchEvent(new Event('change', { bubbles: true }));
                            }"""
                        )
            except Exception:
                pass

    continue_btn = await resolve_locator(page, creds.get("send_otp_selector", "button:has-text('Continue')"))
    if continue_btn is not None:
        await continue_btn.click()

    try:
        await page.locator(creds.get("otp_selector", "[data-testid='otpVerify_otpInputs']")).first.wait_for(
            state="visible", timeout=10000,
        )
    except Exception:
        await page.wait_for_timeout(2000)

    await fill_otp(page, password, creds.get("otp_selector", "input[placeholder*='OTP' i]"))

    submit_btn = await resolve_locator(page, creds.get("submit_selector", "button:has-text('Continue')"))
    if submit_btn is not None:
        await submit_btn.click()

    try:
        await page.wait_for_url(
            lambda url: "/login" not in urlparse(url).path.rstrip("/"),
            timeout=20000,
        )
    except Exception:
        pass


async def perform_login(page: Page, creds: dict[str, str], *, skip_navigation: bool = False) -> None:
    username = creds.get("username", "")
    password = creds.get("password", "")
    login_url = creds.get("login_url") or creds.get("app_url") or ""
    if not (username and password and login_url):
        raise ValueError("Incomplete automation credentials for login")

    login_type = creds.get("login_type", "email_password")

    if not skip_navigation:
        await page.goto(login_url, wait_until="load", timeout=30000)
        try:
            await page.wait_for_load_state("networkidle", timeout=12000)
        except Exception:
            pass
    elif login_type == "phone_otp":
        await wait_for_phone_field(page, creds)

    if login_type == "phone_otp":
        await perform_phone_otp_login(page, creds)
    else:
        email_field = await resolve_locator(page, creds.get("email_selector", "input[type=email]"))
        if email_field is None:
            raise RuntimeError("Email input not found")
        await email_field.fill(username)
        password_field = await resolve_locator(page, creds.get("password_selector", "input[type=password]"))
        if password_field is None:
            raise RuntimeError("Password input not found")
        await password_field.fill(password)
        submit_btn = await resolve_locator(page, creds.get("submit_selector", "button:has-text('Sign in')"))
        if submit_btn is not None:
            await submit_btn.click()

        try:
            await page.wait_for_url(
                lambda url: "/login" not in urlparse(url).path.rstrip("/"),
                timeout=20000,
            )
        except Exception:
            pass
        try:
            await page.wait_for_load_state("networkidle", timeout=12000)
        except Exception:
            pass

    try:
        await page.wait_for_load_state("networkidle", timeout=8000)
    except Exception:
        pass

    if login_type == "phone_otp":
        try:
            await page.wait_for_url(
                lambda url: "/login" not in urlparse(url).path.rstrip("/"),
                timeout=20000,
            )
        except Exception:
            pass
        try:
            await page.wait_for_load_state("networkidle", timeout=8000)
        except Exception:
            pass
