# Generated by QualityPilot — test case ea8925d6-8dd9-45b6-85b0-88f9e0489930
# Title: Regression KAN-8: UI Mismatch: 'Test Cases' tab displays 'New Test' instead of 'New Test Case'
# Feature: Regression / Default
import pytest

pytestmark = pytest.mark.asyncio


async def test_regression_kan_8_ui_mismatch_test_cases_tab_displays_new_tes(page, base_url):
    # Navigate to the Test Cases page
    target_url = base_url.rstrip('/') + '/workspace/617982e3-01a7-48c3-a1f5-990bb26be754/project/994e2044-9d2e-490e-b152-274d01fc73a2/tests'
    await page.goto(target_url)
    
    try:
        await page.wait_for_load_state('networkidle', timeout=8000)
    except Exception:
        pass

    # Locate the action button for creating a new test case.
    # Based on the requirement, we are looking for the button that should be labeled 'New Test Case'.
    # We use get_by_role to find the button.
    new_test_case_button = page.get_by_role('button', name='New Test Case')
    
    # Wait for the button to be visible
    await new_test_case_button.wait_for(state='visible', timeout=8000)
    
    # Assert that the button exists and has the correct text.
    # If the bug exists (labeled 'New Test'), this assertion will fail.
    is_visible = await new_test_case_button.is_visible()
    assert is_visible, "The 'New Test Case' button should be visible on the page."
    
    # Verify the exact text content to ensure it is not 'New Test'
    button_text = await new_test_case_button.inner_text()
    assert button_text.strip() == 'New Test Case', f"Expected button text to be 'New Test Case', but found '{button_text}'"
