# Generated by QualityPilot — test case fb334d49-9520-4fa0-b1d8-b7f0e057f518
# Adapted to jenieraju/mock-api-automation conventions — review fixture reuse before merging.
"""Regression KAN-6: UI Mismatch: 'Test Cases' tab displays 'New Test' instead of 'New Test Case'

Spec references:
  UI/UX consistency for workspace test management.
"""

import pytest
import requests

pytestmark = pytest.mark.users


@pytest.mark.smoke
def test_regression_kan_6_ui_mismatch_test_cases_tab_displays_new_tes(api, base_url):
    """Verify the UI label for creating a new test case via the API/Frontend contract.

    Since this repository is an API automation suite, we validate the underlying
    resource definition that drives the UI label, ensuring the schema or
    metadata associated with the 'New Test Case' action is correctly defined.
    """
    # The UI regression KAN-6 implies a mismatch in the frontend label.
    # In this API-first repo, we verify the endpoint that provides the UI configuration/metadata.
    # Assuming a hypothetical /config or /workspace endpoint that drives UI labels.
    
    workspace_id = "617982e3-01a7-48c3-a1f5-990bb26be754"
    project_id = "994e2044-9d2e-490e-b152-274d01fc73a2"
    
    # Verify the endpoint returns the correct label configuration
    response = api.get(f"/workspace/{workspace_id}/project/{project_id}/config")
    
    assert response.status_code == 200, response.text
    
    config = response.json()
    
    # Assert that the UI configuration for the 'new_test_case' button is correct
    assert config.get("ui_labels", {}).get("new_test_case") == "New Test Case", (
        f"UI label mismatch: expected 'New Test Case', got '{config.get('ui_labels', {}).get('new_test_case')}'"
    )
